[[zones]]
id = "Europe/London"
name = "London"

[[zones]]
id = "America/Chicago"
name = "Chicago"

[[zones]]
id = "America/Los_Angeles"
name = "LA"

[[zones]]
id = "UTC"
name = "UTC"

[keymaps]
prev_minute = ["-"]
next_minute = ["+"]
zero_minute = ["0"]
prev_hour = ["h", "left"]
next_hour = ["l", "right"]
prev_day = ["H", "up"]
next_day = ["L", "down"]
prev_week = ["p", "<"]
next_week = ["n", ">"]
prev_line_select = ["k"]
next_line_select = ["j"]
next_format_style = ["f"]
prev_format_style = ["F"]
next_zone_style = ["z"]
prev_zone_style = ["Z"]
toggle_date = ["d"]
open_web = ["o", "x"]
now = ["t"]
help = ["?"]
quit = ["q", "esc", "ctrl+c"]
