# vim: ft=dosini
#
# aerc matte-black styleset
# set styleset-name=matte-black.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#333333
border.bg=#121212

title.fg=#121212
title.bg=#e68e0d
title.bold=true

header.fg=#D35F5F
#header.bg=#121212
header.bold=true

tab.fg=#8a8a8d
tab.bg=#121212
tab.selected.fg=#121212
tab.selected.bg=#e68e0d

statusline_default.fg=#bebebe
statusline_default.bg=#121212
statusline_error.fg=#D35F5F
statusline_success.fg=#FFC107

*error.bold=true
*error.fg=#D35F5F
*warning.fg=#f59e0b
*success.fg=#FFC107

dirlist_*.bg=#121212
dirlist_*.fg=#bebebe
dirlist_*.selected.bg=#333333
dirlist_*.selected.fg=#ffffff

msglist_*.bg=#121212
msglist_*.fg=#bebebe
msglist_*.selected.bg=#333333
#msglist_*.selected.fg=#ffffff
msglist_unread.bold=true
msglist_unread.fg=#e68e0d
msglist_marked.fg=#FFC107
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#121212
msglist_pill.bg=#333333
msglist_pill.reverse=false

part_*.fg=#bebebe
part_*.bg=#121212
part_*.selected.fg=#ffffff
part_*.selected.bg=#333333

completion_default.bg=#121212
completion_default.fg=#bebebe
completion_default.selected.bg=#333333
completion_default.selected.fg=#ffffff
completion_gutter.bg=#121212
completion_pill.bg=#333333
completion_pill.reverse=false

spinner.bg=#121212
spinner.fg=#e68e0d

selector_focused.bold=false
selector_focused.bg=#333333
selector_focused.fg=#ffffff
selector_chooser.bold=false
selector_chooser.bg=#333333
selector_chooser.fg=#ffffff
default.selected.bold=false
default
