# == Matte Black Theme for Kitty ==

# - Basics -
foreground              #c5c8c6
background              #181818
selection_foreground    #181818
selection_background    #b4b7b4
cursor                  #8a8a8a
cursor_text_color       #181818
url_color               #81a2be

# - Window borders -
active_border_color     #4d4d4d
inactive_border_color   #282828
bell_border_color       #cc6666

# - Tab bar -
active_tab_foreground   #181818
active_tab_background   #c5c8c6
inactive_tab_foreground #8a8a8a
inactive_tab_background #282828
tab_bar_background      #181818

# - The 16 ANSI Colors -

# black
color0  #181818
color8  #585858

# red
color1  #cc6666
color9  #d54e53

# green
color2  #b5bd68
color10 #b9ca4a

# yellow
color3  #f0c674
color11 #e7c547

# blue
color4  #81a2be
color12 #7aa6da

# magenta
color5  #b294bb
color13 #c397d8

# cyan
color6  #8abeb7
color14 #70c0b1

# white
color7  #c5c8c6
color15 #eaeaea
