#!/bin/bash

case "$1" in
"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
"C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-w")      
  if [[ $XDG_CURRENT_DESKTOP == 'Hyprland' ]]; then 
    while read file; do 
      ff="$(readlink -e "${file}")"
      hyprctl hyprpaper unload all && hyprctl hyprpaper preload "$ff" && hyprctl hyprpaper wallpaper "eDP-1,$ff" 
      sed -i "
      s|^\(preload = \).*|\1$ff|
      s|^\(wallpaper = ,\).*|\1$ff|
      " "$HOME/.config/hypr/hyprpaper.conf"
    done
  else
    while read file; do 
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$(readlink -e $file)"
  done
  fi
  ;;
"C-d")      while read file; do rm "$(readlink -e "${file}")"; done ;;
esac
