# vim: ft=dosini
#
# aerc Osaka Jade styleset
# set styleset-name=osaka-jade.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#53685B
border.bg=#111c18

title.fg=#111c18
title.bg=#509475
title.bold=true

header.fg=#FF5345
#header.bg=#111c18
header.bold=true

tab.fg=#53685B
tab.bg=#111c18
tab.selected.fg=#111c18
tab.selected.bg=#509475

statusline_default.fg=#C1C497
statusline_default.bg=#111c18
statusline_error.fg=#FF5345
statusline_success.fg=#2DD5B7

*error.bold=true
*error.fg=#FF5345
*warning.fg=#E5C736
*success.fg=#2DD5B7

dirlist_*.bg=#111c18
dirlist_*.fg=#C1C497
dirlist_*.selected.bg=#23372B
dirlist_*.selected.fg=#C1C497

msglist_*.bg=#111c18
msglist_*.fg=#C1C497
msglist_*.selected.bg=#23372B
#msglist_*.selected.fg=#C1C497
msglist_unread.bold=true
msglist_unread.fg=#509475
msglist_marked.fg=#E5C736
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#23372B
msglist_pill.bg=#53685B
msglist_pill.reverse=false

part_*.fg=#C1C497
part_*.bg=#111c18
part_*.selected.fg=#C1C497
part_*.selected.bg=#53685B

completion_default.bg=#111c18
completion_default.fg=#C1C497
completion_default.selected.bg=#53685B
completion_default.selected.fg=#C1C497
completion_gutter.bg=#23372B
completion_pill.bg=#53685B
completion_pill.reverse=false

spinner.bg=#111c18
spinner.fg=#C1C497

selector_focused.bold=false
selector_focused.bg=#23372B
selector_focused.fg=#C1C497
selector_chooser.bold=false
selector_chooser.bg=#23372B
selector_chooser.fg=#C1C497
default.selected.bold=false
default.selected.fg=#C1C497
default.selected.bg=#23372B

[viewer]
url.underline=true
url.fg=#ACD4CF
header.fg=#D2689C
signature.fg=#D2689C
diff_add.fg=#162A21
diff_del.fg=#2E1D1D
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#E5C736
quote_2.fg=#549e6a
quote_3.fg=#2DD5B7
quote_3.dim=true
quote_4.fg=#509475
quote_4.dim=true
quote_x.fg=#53685B
quote_x.dim=true
