# vim:ft=kitty

background #111c18
foreground #C1C497
selection_background #C1C497
selection_foreground #111C18
url_color #2DD5B7
cursor #D7C995
cursor_text_color #111c18

# Tabs
active_tab_background #509475
active_tab_foreground #111c18
inactive_tab_background #23372B
inactive_tab_foreground #53685B
#tab_bar_background #111c18

# Windows
active_border_color #509475
inactive_border_color #23372B

# normal
color0 #23372B
color1 #FF5345
color2 #549e6a
color3 #459451
color4 #509475
color5 #D2689C
color6 #2DD5B7
color7 #F6F5DD

# bright
color8  #53685B
color9  #db9f9c
color10 #63b07a
color11 #E5C736
color12 #ACD4CF
color13 #75bbb3
color14 #8CD3CB
color15 #9eebb3

# extended colors
color16 #E5C736
color17 #db9f9c
