[window]
decorations = "None"
opacity = 0.9

  [window.dimensions]
  columns = 100
  lines = 27

  [window.padding]
  x = 3
  y = 3

[font]
size = 13

  [font.bold]
  family = "MesloLGS Nerd Font"
  style = "Bold"

  [font.bold_italic]
  family = "MesloLGS Nerd Font"
  style = "Bold Italic"

  [font.italic]
  family = "MesloLGS Nerd Font"
  style = "Italic"

  [font.normal]
  family = "MesloLGS Nerd Font"
  style = "Regular"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

  [colors.primary]
  background = "#000000"
  foreground = "#ffffff"

  [colors.cursor]
  text = "#000000"
  cursor = "#ffffff"

  [colors.normal]
  black = "#151515"
  red = "#bf7979"
  green = "#97b26b"
  yellow = "#cdcda1"
  blue = "#4a5463"
  magenta = "#9c3885"
  cyan = "#88aadd"
  white = "#ffffff"

  [colors.bright]
  black = "#505450"
  red = "#f4a45f"
  green = "#c5f779"
  yellow = "#ffffaf"
  blue = "#7d8794"
  magenta = "#e628ba"
  cyan = "#99ccff"
  white = "#dedede"

[cursor]
unfocused_hollow = true

  [cursor.style]
  shape = "Block"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
chars = "\u001b[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001b[13;5u"
key = "Return"
mods = "Control"
